export const WEB_CLIENT = `
const byId=(id)=>document.getElementById(id);
const translations={
  "概览":"Overview","接入":"Connection","上游":"Upstream","会话":"Sessions","设置":"Settings",
  "客户端接入":"Client connection","上游网络":"Upstream network","高级设置":"Advanced settings","服务地址":"Service address","客户端接入":"Client connection",
  "刷新":"Refresh","保存并热更新":"Save and hot-reload","测试连接":"Test connection","保存覆盖并热更新":"Save overrides and hot-reload","保存并应用":"Save and apply",
  "复制":"Copy","复制配置":"Copy config","复制 CA 路径":"Copy CA path","恢复压缩":"Restore compression","处理中…":"Working…","复制中…":"Copying…","保存中…":"Saving…","测试中…":"Testing…","刷新中…":"Refreshing…",
  "直连（默认）":"Direct (default)","手动代理":"Manual proxy","自动（跟随系统）":"Automatic (system)","当前来源":"Current source","有效代理":"Effective proxy","系统 PAC":"System PAC","状态":"Status","尚未测试":"Not tested","暂无会话":"No sessions",
  "标题":"Title","协议":"Protocol","标识":"Identifier","请求":"Requests","上下文":"Context","最后活动":"Last activity","恢复，开机后未活动":"restored; inactive since startup",
  "全局代理":"Global proxy","按 URL 覆盖":"Per-URL overrides","Provider URL":"Provider URL","上游代理（空=继承全局）":"Upstream proxy (empty = inherit global)","加载中":"Loading",'暂无 Provider。在"高级设置"页添加 Provider 后可在此按 URL 配置代理。':"No providers. Add one on the Advanced settings page to configure a per-URL proxy here.","继承全局":"Inherit global",
  "连接成功，HTTP ":"Connection successful, HTTP ","连接失败":"Connection failed","直连":"Direct","CONNECT 正常":"CONNECT OK","上游设置已热更新":"Upstream settings hot-reloaded","Provider 配置已热更新":"Provider configuration hot-reloaded","压缩参数已热更新":"Compression settings hot-reloaded","按 URL 覆盖已热更新":"Per-URL overrides hot-reloaded","已复制":"Copied","已恢复压缩":"Compression restored","会话列表已刷新":"Session list refreshed",
  "配置文件":"Config file","baseURL":"baseURL","base_url":"base_url","认证":"Authentication","说明":"Notes",'默认 provider 就是 openai，无需 model_provider；若 config.toml 里改过 ' :"The default provider is openai; model_provider is not required. If config.toml changes ",'连不上时检查代理环境变量：设了 HTTP(S)_PROXY 需加 ' :"If it cannot connect, check proxy environment variables: when HTTP(S)_PROXY is set, add ","方式":"Method","设置":"Settings","CA 证书":"CA certificate","环境变量":"Environment variable","规则":"Rule","示例":"Example",
  "Passthrough 已启用":"Passthrough enabled","环境变量 ACP_PASSTHROUGH（或 --passthrough 参数）":"ACP_PASSTHROUGH environment variable (or --passthrough flag)","配置文件 passthrough: true":"passthrough: true in config file",'在"接入"页将各客户端（Codex / Claude Code / OpenCode / Pi 等）的流量路由到 bili。':"Route traffic from clients (Codex / Claude Code / OpenCode / Pi, etc.) to bili on the Connection page.","本地路由与上游网络相互独立。ACP 压缩运行在两者之间。":"Local routing and upstream networking are independent. ACP compression runs between them.","本地路由与上游网络相互独立，ACP 压缩运行在两者之间。":"Local routing and upstream networking are independent; ACP compression runs between them.","控制 bili 如何访问真实 Provider，不会改变客户端的本地路由地址。":"Control how bili reaches the real provider without changing the client-facing local route.","ACP 压缩状态与上游用量。":"ACP compression state and upstream usage.","直接编辑 providers JSON（添加新 Provider、配置模型上下文窗口、按 URL 代理等）；保存后立即热更新。":"Edit providers JSON directly (add providers, configure model context windows, per-URL proxies, and more); changes hot-reload immediately.","保存后热更新，无需重启。置空 = 恢复默认。":"Changes hot-reload without a restart."
};
let english=false;
function translateText(value){let text=String(value??"");for(const [zh,en] of Object.entries(translations).sort(([a],[b])=>b.length-a.length))text=text.split(zh).join(en);return text}
function applyLanguage(){document.documentElement.lang=english?"en":"zh-CN";document.querySelectorAll("body *:not(script):not(style)").forEach((node)=>{if(node.children.length===0&&node.textContent)node.textContent=translateText(node.textContent)});document.querySelectorAll("input,textarea").forEach((node)=>{if(node.placeholder)node.placeholder=translateText(node.placeholder)});const toggle=byId("language-toggle");if(toggle)toggle.textContent=english?"中文":"English";localStorage.setItem("bili-language",english?"en":"zh");if(english){document.querySelectorAll(".copy-btn").forEach((node)=>{if(node.textContent)node.textContent=translateText(node.textContent)});loadUpstream().catch(()=>{})}}
function toggleLanguage(){location.reload()}
const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
function toast(message,error){const node=byId("toast");node.textContent=message;node.className="toast show"+(error?" err":"");setTimeout(()=>node.className="toast"+(error?" err":""),2600)}
function busy(button,on,label){if(!button)return;if(on){button.dataset.label=button.textContent;button.textContent=label||"处理中…";button.disabled=true;return}if(button.dataset.label){button.textContent=button.dataset.label;delete button.dataset.label}button.disabled=false}
async function json(url,options){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||data.detail||("HTTP "+response.status));return data}
function showPage(name){document.querySelectorAll(".page").forEach((node)=>node.classList.toggle("active",node.id==="page-"+name));document.querySelectorAll(".nav button").forEach((node)=>node.classList.toggle("active",node.dataset.page===name));if(name==="sessions")loadSessions();if(name==="upstream"){loadUpstream();loadOverrides()}}
document.querySelectorAll(".nav button").forEach((button)=>button.addEventListener("click",()=>showPage(button.dataset.page)));
const savedLanguage=localStorage.getItem("bili-language");if(savedLanguage==="en")english=true;
byId("language-toggle").addEventListener("click",()=>{localStorage.setItem("bili-language",english?"zh":"en");toggleLanguage()});applyLanguage();
async function loadConfig(){const data=await json("/__bili/config");if(data.parseError)toast(String(data.parseError),true);byId("providers-json").value=JSON.stringify(data.providers||{},null,2);byId("proxy-url").value=data.upstreamProxy||"";byId("compress-json").value=data.compress?JSON.stringify(data.compress,null,2):"";document.querySelectorAll('input[name="proxy-mode"]').forEach((input)=>input.checked=input.value===(data.upstreamProxyMode||"direct"));const pt=data.passthrough||{enabled:false};const banner=byId("passthrough-banner");if(banner){if(pt.enabled){banner.hidden=false;byId("passthrough-source").textContent=english?"ACP_PASSTHROUGH environment variable (or --passthrough flag)":pt.source==="env"?"环境变量 ACP_PASSTHROUGH（或 --passthrough 参数）":"配置文件 passthrough: true";const btn=byId("clear-passthrough");btn.disabled=pt.source==="env";btn.title=pt.source==="env"?(english?"Unset ACP_PASSTHROUGH and restart first":"需先 unset ACP_PASSTHROUGH 并重启"):""}else{banner.hidden=true}}return data}
async function loadUpstream(){try{const data=await json("/__bili/upstream");const labels={"provider":english?"Provider proxy":"Provider 单独代理","provider-direct":english?"Provider direct":"Provider 直连","bili-env":"BILI_UPSTREAM_PROXY","web-manual":english?"Web manual proxy":"Web 手动代理","config":english?"Config file proxy":"配置文件代理","HTTPS_PROXY":"HTTPS_PROXY","HTTP_PROXY":"HTTP_PROXY","ALL_PROXY":"ALL_PROXY","windows-system":"Windows system proxy","windows-bypass":"Windows bypass list","no-proxy":"NO_PROXY","direct":english?"Direct":"直连"};byId("upstream-source").textContent=labels[data.source]||data.source||(english?"Direct":"直连");byId("upstream-effective").textContent=data.proxy||"direct";byId("upstream-pac").textContent=data.autoConfigUrl||"—";const state=byId("upstream-state");state.className="status "+(data.connected===true?"ok":data.connected===false?"err":"");state.textContent=data.connected===true?(english?"CONNECT OK":"CONNECT 正常"):data.connected===false?(data.error||(english?"Connection failed":"连接失败")):(english?"Not tested":"尚未观察到上游连接")}catch(error){byId("upstream-state").textContent=String(error)}}
async function saveUpstream(){const button=byId("save-upstream");busy(button,true,"保存中…");const mode=document.querySelector('input[name="proxy-mode"]:checked').value;try{await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({upstreamProxyMode:mode,upstreamProxy:byId("proxy-url").value.trim()||null})});toast("上游设置已热更新");await loadUpstream()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function testUpstream(){const button=byId("test-upstream");busy(button,true,"测试中…");try{const data=await json("/__bili/upstream/test",{method:"POST"});toast("连接成功，HTTP "+data.status);await loadUpstream()}catch(error){toast(String(error),true);await loadUpstream()}finally{busy(button,false)}}
async function saveProviders(){const button=byId("save-providers");busy(button,true,"保存中…");try{const providers=JSON.parse(byId("providers-json").value);await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({providers})});await json("/__bili/config/reload",{method:"POST"});toast("Provider 配置已热更新")}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function saveCompress(){const button=byId("save-compress");busy(button,true,"保存中…");try{const text=byId("compress-json").value.trim();const compress=text?JSON.parse(text):null;await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({compress})});toast("压缩参数已热更新")}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function loadOverrides(){try{const data=await loadConfig();const providers=data.providers||{};const box=byId("upstream-overrides");const entries=Object.entries(providers);if(entries.length===0){box.innerHTML='<p class="status">暂无 Provider。在"高级设置"页添加 Provider 后可在此按 URL 配置代理。</p>';return}box.innerHTML='<table><thead><tr><th>Provider URL</th><th>上游代理（空=继承全局）</th></tr></thead><tbody>'+entries.map(([url,route])=>'<tr><td class="mono">'+escapeHtml(url)+'</td><td><input class="mono override-proxy" data-url="'+escapeHtml(url)+'" value="'+escapeHtml((route&&route.proxy)||"")+'" placeholder="继承全局"></td></tr>').join("")+'</tbody></table>'}catch(error){byId("upstream-overrides").textContent=String(error)}}
async function saveOverrides(){const button=byId("save-overrides");busy(button,true,"保存中…");try{const data=await loadConfig();const providers=data.providers||{};document.querySelectorAll(".override-proxy").forEach((input)=>{const url=input.dataset.url;if(!url)return;if(!providers[url])providers[url]={};const val=input.value.trim();if(val)providers[url].proxy=val;else delete providers[url].proxy});await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({providers})});await json("/__bili/config/reload",{method:"POST"});toast("按 URL 覆盖已热更新");await loadOverrides()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function loadSessions(){try{const data=await json("/__bili/stats");const rows=(data.sessions||[]).map((item)=>"<tr><td>"+escapeHtml(item.title||"—")+"</td><td>"+escapeHtml(item.protocol||"—")+"</td><td class=mono>"+escapeHtml(item.label||"—")+"</td><td>"+escapeHtml(item.requests)+"</td><td>"+escapeHtml(item.contextTokens)+"</td><td>"+escapeHtml(new Date(item.lastSeen).toLocaleString())+(item.restored?" <span class=muted>(恢复，开机后未活动)</span>":"")+"</td></tr>").join("");byId("sessions-body").innerHTML=rows||'<tr><td colspan="6">暂无会话</td></tr>'}catch(error){toast(String(error),true);throw error}}
async function refreshSessions(){const button=byId("refresh-sessions");busy(button,true,"刷新中…");try{await loadSessions();toast("会话列表已刷新")}catch{}finally{busy(button,false)}}
document.querySelectorAll(".copy-btn").forEach((btn)=>btn.addEventListener("click",async()=>{busy(btn,true,"复制中…");try{await navigator.clipboard.writeText(btn.dataset.copy||"");toast("已复制")}catch(e){toast(String(e),true)}finally{busy(btn,false)}}));async function clearPassthrough(){const button=byId("clear-passthrough");busy(button,true,"处理中…");try{await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({passthrough:null})});toast("已恢复压缩");await loadConfig()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
byId("clear-passthrough").addEventListener("click",clearPassthrough);
byId("save-upstream").addEventListener("click",saveUpstream);byId("test-upstream").addEventListener("click",testUpstream);byId("save-providers").addEventListener("click",saveProviders);byId("save-compress").addEventListener("click",saveCompress);byId("save-overrides").addEventListener("click",saveOverrides);byId("refresh-sessions").addEventListener("click",refreshSessions);
Promise.all([loadConfig(),loadUpstream()]).catch((error)=>toast(String(error),true));setInterval(()=>{if(byId("page-sessions").classList.contains("active"))loadSessions().catch(()=>{})},5000);
`;
